id: PAEF08C34
initial_creation_type: input
source_metadata:
  title: Minyak Kunzang Sönam Series
  language: fr
  description: 'Texts by and about Minyak Kunzang Sönam (mi nyag kun bzang bsod nams,
    1823–1905) alias Thubten Chökyi Drakpa (thub bstan chos kyi grags pa) :'
  volume:
    41241abdeaaa42f8a65f6150565afea7:
      title: Overview of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
created_at: '2022-03-01T00:49:12.158591'
last_modified_at: '2022-03-01T00:49:12.158595'
